### ISSUE TITLE
inverse unrugPercent

### ISSUE THREAD

**Issue by fico23** [NaniDAO/accounts#17]
https://github.com/NaniDAO/accounts/blob/615327f8c1022e4e79eb10d0a1c7fa40554d087a/src/AccountUNRG.sol#L21

`if (balanceAfter >= balanceBefore) return result;
        unchecked {
            if ((balanceBefore - balanceAfter) > (balanceBefore * unrugPercent / 100)) {
                revert Unauthorized();
            }
        }`

if unrugPercent become rugPercent, this can be simplified to:
`if (balanceAfter * 100 / balanceBefore < rugPercent) revert Unauthorized()`

there's an extra case for division by zero, which can be handled in a few ways

**Comment by z0r0z** [comment]
thank you @fico23 This looks clean and the comparison is helpful. I'd like to make this nit in the unrug branch as an improvement, but feel free to throw up a pr in the meantime.

**Comment by z0r0z** [comment]
& integrated here, @fico23 https://github.com/NaniDAO/accounts/commit/7de36a3d39c803832cd611fb5f109f5ac92c99ae

**Comment by fico23** [comment]
speaking of unrug feature; this only works for native token, smart wallet should be able to handle ERC20s as well.
since all ERC20s need to be approved prior to transfering, you can know when some ERC20 is leaving wallet and you can check for unrugPercent, with the invariant that after series of external calls is done, all approvals must be == 0.
We do something similar with Aera Finance, which is a treasury management protocol. You can see details [here](https://github.com/aera-finance/aera-contracts-public/blob/d21a65f516d142d89c99363140650d90de5bb8b7/v2/AeraVaultHooks.sol#L296)
